import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import { CheckCircle2, FileDiff, History, RotateCcw, Save, ShieldCheck, XCircle } from 'lucide-react'
import { APIClient } from './api'
import { ReadableMarkdown } from './ReadableContent'

type Asset = { asset_id:string; asset_type:string; title:string; summary:string; status:string; version:string; risk_level:string; source_memory_ids:string[]; validation_status:string; classification_status?:string; classification_scores?:Record<string,number>; classification_reasons?:string[]; created_at:string; updated_at:string }
type Revision = { object_id:string; revision:number; status:string; payload:Record<string,unknown>; content_hash:string; confidence:number; importance:number; plugin_id:string; plugin_version:string; created_at:string }
type ObjectEnvelope = { object_id:string; type_id:string; project_id:string; status:string; current_revision:number; revision:Revision }
type RevisionReview = { review_id:string; object_id:string; revision:number; base_revision:number; status:string; target_status:string; requested_by:string; decision_by?:string; decision_note?:string; diff:Record<string,unknown>; validation:Record<string,unknown>; rollback_from_revision?:number; created_at:string; decided_at?:string; activated_at?:string; proposed_revision:Revision }
type Detail = { asset:Asset; memories:Array<Record<string,unknown>>; governance?:{ object:ObjectEnvelope; revisions:Revision[]; reviews:RevisionReview[] } }
type TemplateField={key:string;label:string;description:string;kind:'text'|'list';required:boolean;placeholder:string}
type AssetTemplate={asset_type:string;label:string;description:string;template_version:string;fields:TemplateField[]}

const typeCopy:Record<string,string>={prompt:'Prompt · 提示资产',skill:'Skill · 技能',rule:'Rule · 规则',constraint:'Constraint · 强约束',procedure:'Procedure · 流程',tool_recipe:'Tool Recipe · 工具配方',mcp:'MCP · 工具合同',unclassified:'Unclassified · 待人工分类'}
function when(value?:string){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
const validationCopy:Record<string,string>={passed:'验证通过',manual_passed:'人工通过',warning:'警告',failed:'验证失败',not_executed:'未执行',not_run:'未运行'}
function validationStatusLabel(value:unknown){const key=String(value||'not_run');return validationCopy[key]||key}
function validationLabel(review:RevisionReview){return validationStatusLabel(review.validation?.status)}
function validationBlocked(review:RevisionReview){return String(review.validation?.status||'not_run')==='failed'}

function RevisionDiff({ review }: { review: RevisionReview }) {
  const before = review.diff?.before && typeof review.diff.before === 'object' ? review.diff.before as Record<string,unknown> : {}
  const after = review.diff?.after && typeof review.diff.after === 'object' ? review.diff.after as Record<string,unknown> : {}
  const fields = Array.isArray(review.diff?.changed_fields) ? review.diff.changed_fields as string[] : []
  if (!fields.length) return <p>没有检测到内容字段变化；请检查生命周期或回滚元数据。</p>
  return <div className="revision-diff">{fields.map(field => <section key={field}><h4>{field}</h4><div><article><small>BEFORE</small><pre>{JSON.stringify(before[field] ?? null, null, 2)}</pre></article><article><small>AFTER</small><pre>{JSON.stringify(after[field] ?? null, null, 2)}</pre></article></div></section>)}</div>
}

function ValidationReport({ review }: { review: RevisionReview }) {
  const checks = Array.isArray(review.validation?.checks) ? review.validation.checks.filter(item => item && typeof item === 'object') as Array<Record<string,unknown>> : []
  const validator = String(review.validation?.validator || '')
  return <section className="asset-validation-report"><header><div><ShieldCheck size={14}/><strong>服务端验证</strong></div><span className={`validation-state state-${String(review.validation?.status||'not_run')}`}>{validationLabel(review)}</span></header>{validator&&<code>{validator}</code>}<div>{checks.length?checks.map((check,index)=>{const status=String(check.status||'not_run');const data=check.data&&typeof check.data==='object'?check.data as Record<string,unknown>:undefined;return <article key={`${String(check.name||'check')}-${index}`} className={`validation-check state-${status}`}><div><strong>{String(check.name||'check')}</strong><span>{validationStatusLabel(status)}</span></div><p>{String(check.detail||'')}</p>{data&&Object.keys(data).length>0&&<pre>{JSON.stringify(data,null,2)}</pre>}</article>}):<p className="validation-empty">该 Revision 没有逐项验证记录。</p>}</div><small>warning 需要 Owner 判断；not_executed 表示验证器明确没有执行外部副作用。</small></section>
}

export function AssetGovernanceDrawer({api,assetID,onClose,onChanged}:{api:APIClient;assetID:string;onClose:()=>void;onChanged?:()=>void}){
  const [detail,setDetail]=useState<Detail>(); const [templates,setTemplates]=useState<AssetTemplate[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [notice,setNotice]=useState('')
  const [mode,setMode]=useState<'current'|'edit'|'history'>('current'); const [saving,setSaving]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError('');try{const nextDetail=await api.get<Detail>(`/v1/assets/${encodeURIComponent(assetID)}`);setDetail(nextDetail);try{const templateResult=await api.get<{templates:AssetTemplate[]}>('/v1/asset-templates');setTemplates(templateResult.templates||[])}catch{setTemplates([])}}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[api,assetID])
  useEffect(()=>{void load()},[load])
  const governance=detail?.governance; const object=governance?.object; const payload=(object?.revision.payload||{}) as Record<string,unknown>
  const isV4=object?.type_id==='builtin.agent-assets.governed-asset.v4'; const template=templates.find(item=>item.asset_type===String(payload.asset_type||detail?.asset.asset_type)); const spec=(payload.spec&&typeof payload.spec==='object'?payload.spec:{}) as Record<string,unknown>
  const pending=useMemo(()=>governance?.reviews.filter(item=>item.status==='pending')||[],[governance])
  async function propose(event:FormEvent<HTMLFormElement>){event.preventDefault();const currentObject=detail?.governance?.object;if(!currentObject||!detail)return;setSaving(true);setError('');setNotice('');const form=new FormData(event.currentTarget);let nextPayload:Record<string,unknown>;if(isV4&&template){const nextSpec=Object.fromEntries(template.fields.map(field=>{const value=String(form.get(`spec.${field.key}`)||'').trim();return [field.key,field.kind==='list'?value.split('\n').map(item=>item.trim().replace(/^[-*]\s*/, '')).filter(Boolean):value]}));const priorRefinement=payload.refinement&&typeof payload.refinement==='object'?payload.refinement as Record<string,unknown>:{};nextPayload={...payload,title:String(form.get('title')||'').trim(),summary:String(form.get('summary')||'').trim(),spec:nextSpec,refinement:{...priorRefinement,mode:'owner_edit',generated_at:new Date().toISOString(),missing_fields:[]},validation_status:'not_run'}}else{nextPayload={...currentObject.revision.payload,asset_id:detail.asset.asset_id,asset_type:String(form.get('asset_type')||detail.asset.asset_type),title:String(form.get('title')||''),body:String(form.get('body')||''),source_memory_ids:detail.asset.source_memory_ids||[],validation_status:'passed'}}try{await api.post(`/v1/harness/objects/${encodeURIComponent(currentObject.object_id)}/revisions`,{payload:nextPayload,expected_revision:currentObject.current_revision,edit_reason:String(form.get('edit_reason')||'').trim(),target_status:'active',idempotency_key:`owner-edit-${Date.now()}`,validation:{status:'not_run'}});setNotice('新修订已创建，但尚未生效；请在下方 Diff 或“待我审核”确认后激活。');setMode('history');await load();onChanged?.()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
  async function decide(reviewID:string,decision:'approve'|'reject'){setSaving(true);setError('');try{await api.post(`/v1/harness/revision-reviews/${encodeURIComponent(reviewID)}/decision`,{decision,note:decision==='approve'?'Owner 检查 Diff 与验证结果后批准':'Owner 拒绝该修订'});setNotice(decision==='approve'?'修订已激活；旧版本仍完整保留。':'修订已拒绝，当前版本没有变化。');await load();onChanged?.()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
  async function rollback(revision:number){const currentObject=detail?.governance?.object;if(!currentObject)return;setSaving(true);setError('');try{await api.post(`/v1/harness/objects/${encodeURIComponent(currentObject.object_id)}/rollback`,{revision});setNotice(`已生成恢复自 R${revision} 的新回滚修订；它仍需审核，不会直接覆盖当前版本。`);setMode('history');await load()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
  async function resolveClassification(assetType:string){setSaving(true);setError('');setNotice('');try{await api.post(`/v1/assets/${encodeURIComponent(assetID)}/classification`,{asset_type:assetType});setNotice(`已人工定类为 ${typeCopy[assetType]||assetType}，并创建 candidate governed object；仍需验证与审核后才能激活。`);await load();onChanged?.()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setSaving(false)}}
  return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="drawer asset-governance-drawer" onMouseDown={event=>event.stopPropagation()}><button className="drawer-close" onClick={onClose} aria-label="关闭">×</button>{loading&&!detail?<div className="governance-loading">正在读取资产版本链…</div>:error&&!detail?<div className="governance-error"><XCircle size={20}/>{error}</div>:detail&&<><p className="micro">GOVERNED AGENT ASSET</p><h2>{detail.asset.title}</h2><div className="drawer-status"><span>{typeCopy[detail.asset.asset_type]||detail.asset.asset_type}</span><span>{governance?.object.status||detail.asset.status}</span><span>{isV4?'V4 标准模板':detail.asset.classification_status||'legacy'}</span><span>{String(payload.validation_status||detail.asset.validation_status)}</span></div>{notice&&<p className="surface-notice">{notice}</p>}{error&&<p className="form-error">{error}</p>}
    {!governance?<section className="governance-missing"><ShieldCheck size={28}/><h3>{detail.asset.asset_type==='unclassified'?'需要 Owner 判断它属于哪一种能力资产':'这个候选还没有进入模板化治理'}</h3>{detail.asset.asset_type==='unclassified'?<><p>确定性分类器选择了 abstain，因此这条内容没有被强塞进 Prompt / Skill / Rule / Constraint / Procedure / Tool Recipe / MCP，也不会暴露给 Agent 执行。</p><div className="manual-classification">{Object.entries(typeCopy).filter(([type])=>type!=='unclassified').map(([type,label])=><button className="button" disabled={saving} key={type} onClick={()=>resolveClassification(type)}>{label}</button>)}</div><small>选择类型后只会创建候选；仍需在能力资产工坊运行“按模板二次沉淀”，并由 Owner 审核后才能激活。</small></>:<><p>这条内容已经完成第一轮定类，但尚未按对应标准模板补齐字段。</p><small>回到能力资产工坊勾选它，点击“按模板二次沉淀”；不需要重跑原材料。</small></>}</section>:<><div className="governance-tabs"><button className={mode==='current'?'active':''} onClick={()=>setMode('current')}>当前版本</button><button className={mode==='edit'?'active':''} onClick={()=>setMode('edit')}>{isV4?'补齐 / 修订模板':'创建修订'}</button><button className={mode==='history'?'active':''} onClick={()=>setMode('history')}>版本与审核 <em>{pending.length}</em></button></div>
    {mode==='current'&&<><section className="governance-current"><div><span>CURRENT REVISION</span><strong>R{governance.object.current_revision}</strong></div><div><span>对象状态</span><strong>{governance.object.status}</strong></div><div><span>类型</span><strong>{typeCopy[String(payload.asset_type)]||String(payload.asset_type)}</strong></div><div><span>格式</span><strong>{isV4?'V4 标准模板':'V3 兼容正文'}</strong></div></section><section className="review-proposal"><small>当前生效内容</small><h3>{String(payload.title||detail.asset.title)}</h3><p>{String(payload.summary||'')}</p>{isV4&&template?<div className="asset-structured-spec">{template.fields.map(field=>{const value=spec[field.key];const values=Array.isArray(value)?value.map(String):[];return <article key={field.key}><strong>{field.label}</strong>{field.kind==='list'?<ul>{values.length?values.map((item,index)=><li key={`${field.key}-${index}`}>{item}</li>):<li className="missing">待补充</li>}</ul>:<p className={!String(value||'').trim()?'missing':''}>{String(value||'待补充')}</p>}</article>})}</div>:<ReadableMarkdown content={String(payload.body||detail.asset.summary)} className="asset-readable-body"/>}</section><p className="drawer-lead">编辑不会覆盖 R{governance.object.current_revision}；它只会追加一个待审核 Revision。只有必填格式与验证都通过并由 Owner 批准后，current pointer 才会切换。</p></>}
    {mode==='edit'&&<form className="asset-revision-form" onSubmit={propose}>{isV4&&template?<><div className="asset-template-heading"><strong>{template.label}</strong><span>{template.description}</span></div><label>标题<input name="title" required maxLength={240} defaultValue={String(payload.title||detail.asset.title)}/></label><label>摘要<textarea name="summary" required maxLength={4000} rows={3} defaultValue={String(payload.summary||detail.asset.summary)}/></label>{template.fields.map(field=><label key={field.key}>{field.label}{field.required&&<b>必填</b>}<small>{field.description}</small><textarea name={`spec.${field.key}`} required={field.required} rows={field.kind==='list'?4:3} placeholder={field.placeholder} defaultValue={field.kind==='list'&&Array.isArray(spec[field.key])?(spec[field.key] as unknown[]).map(String).join('\n'):String(spec[field.key]||'')}/>{field.kind==='list'&&<em>每行一项</em>}</label>)}</>:<><label>资产类型<select name="asset_type" defaultValue={String(payload.asset_type||detail.asset.asset_type)}>{Object.entries(typeCopy).filter(([value])=>value!=='unclassified').map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>标题<input name="title" required maxLength={240} defaultValue={String(payload.title||detail.asset.title)}/></label><label>正文<textarea name="body" required rows={13} defaultValue={String(payload.body||detail.asset.summary)}/></label></>}<label>本次修改原因<input name="edit_reason" required minLength={4} maxLength={500} placeholder="说明为什么修改；会永久写入 Revision 审计"/></label><div className="validation-preview"><CheckCircle2 size={16}/><div><strong>服务端确定性验证</strong><span>{isV4?'模板必填字段 · 来源链 · 类型专项检查 · 冲突检查；缺字段时不能激活':'Schema · 来源链 · 类型专项检查；不会执行外部工具'}</span></div></div><button className="button primary" disabled={saving}><Save size={14}/>{saving?'正在创建 Revision…':'创建待审核 Revision'}</button></form>}
    {mode==='history'&&<div className="revision-history">{pending.map(review=><article className="revision-review-card" key={review.review_id}><header><FileDiff size={16}/><strong>R{review.revision} ← R{review.base_revision}</strong><span>{review.rollback_from_revision?`回滚自 R${review.rollback_from_revision}`:'内容修订'}</span></header><RevisionDiff review={review}/><ValidationReport review={review}/><footer><span>{validationLabel(review)}</span><time>{when(review.created_at)}</time><button className="button" disabled={saving} onClick={()=>decide(review.review_id,'reject')}>拒绝</button><button className="button primary" disabled={saving||validationBlocked(review)} onClick={()=>decide(review.review_id,'approve')}>{validationBlocked(review)?'验证失败，不能激活':'批准并激活'}</button></footer></article>)}<div className="revision-list">{governance.revisions.map(revision=><article key={revision.revision} className={revision.revision===governance.object.current_revision?'current':''}><div><History size={15}/><strong>R{revision.revision}</strong><span>{revision.status}</span>{revision.revision===governance.object.current_revision&&<b>Current</b>}</div><p>{String((revision.payload as Record<string,unknown>).title||'未命名资产')}</p><footer><code>{revision.content_hash.slice(0,12)}</code><time>{when(revision.created_at)}</time>{revision.revision!==governance.object.current_revision&&<button className="text-button" disabled={saving} onClick={()=>rollback(revision.revision)}><RotateCcw size={12}/>恢复此版本</button>}</footer></article>)}</div></div>}
    </>}</>}</aside></div>
}
