import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { KnowledgeProductBlockGovernance } from './KnowledgeProductBlocks'
import { APIClient } from './api'

afterEach(cleanup)
const block={block_id:'section-goals',label:'目标与里程碑',content:'## 目标与里程碑\n- Owner 目标',content_hash:'abcdef123456',locked:true,lock_base_revision:2,lock_base_hash:'basehash1234'}

describe('Knowledge Product block governance',()=>{
  it('updates the full lock set with expected revision',async()=>{
    const get=vi.fn(async()=>({blocks:[block]}))
    const put=vi.fn(async()=>({blocks:[{...block,locked:false}]}))
    render(<KnowledgeProductBlockGovernance api={{get,put} as unknown as APIClient} objectID="obj-brief" currentRevision={4} autoGenerated />)
    fireEvent.click(await screen.findByRole('button',{name:/解除 Block 锁/}))
    await waitFor(()=>expect(put).toHaveBeenCalledWith('/v1/knowledge-products/obj-brief/block-locks',{expected_revision:4,block_ids:[]}))
    expect(await screen.findByText(/下一次自动刷新可重新接管/)).toBeInTheDocument()
  })

  it('shows base current candidate merged and never auto-resolves a divergence',async()=>{
    const get=vi.fn(async(path:string)=>{
      if(path.endsWith('/blocks'))return {blocks:[block]}
      if(path.endsWith('/merge-preview'))return {object_id:'obj-brief',current_revision:4,candidate_body_hash:'candidatehash',merged_body:'Owner 目标',has_conflicts:true,blocks:[{block_id:'section-goals',label:'目标与里程碑',locked:true,base:'BASE goal',current:'CURRENT Owner goal',candidate:'CANDIDATE generated goal',merged:'CURRENT Owner goal',status:'diverged_locked',requires_owner:true}]}
      throw new Error(`unexpected GET ${path}`)
    })
    render(<KnowledgeProductBlockGovernance api={{get,put:vi.fn()} as unknown as APIClient} objectID="obj-brief" currentRevision={4} autoGenerated />)
    fireEvent.click(await screen.findByRole('button',{name:/三方 Merge 预览/}))
    expect(await screen.findByText(/存在锁定分歧/)).toBeInTheDocument()
    fireEvent.click(screen.getByText('diverged_locked').closest('summary')!)
    expect(screen.getByText(/BASE goal/)).toBeInTheDocument()
    expect(screen.getAllByText(/CURRENT Owner goal/)).toHaveLength(2)
    expect(screen.getByText(/CANDIDATE generated goal/)).toBeInTheDocument()
  })
})
