import { useCallback, useEffect, useMemo, useState } from 'react'
import { GitCompareArrows, LockKeyhole, RefreshCw, ShieldAlert, UnlockKeyhole } from 'lucide-react'
import { APIClient } from './api'

type ProductBlock={block_id:string;label:string;content:string;content_hash:string;locked:boolean;lock_base_revision?:number;lock_base_hash?:string}
type MergeBlock={block_id:string;label:string;locked:boolean;base:string;current:string;candidate:string;merged:string;status:string;requires_owner:boolean}
type MergePreview={object_id:string;current_revision:number;candidate_body_hash:string;merged_body:string;has_conflicts:boolean;blocks:MergeBlock[]}

export function KnowledgeProductBlockGovernance({api,objectID,currentRevision,autoGenerated}:{api:APIClient;objectID:string;currentRevision:number;autoGenerated:boolean}){
  const [blocks,setBlocks]=useState<ProductBlock[]>([])
  const [preview,setPreview]=useState<MergePreview>()
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  const load=useCallback(async()=>{setError('');try{const result=await api.get<{blocks:ProductBlock[]}>(`/v1/knowledge-products/${encodeURIComponent(objectID)}/blocks`);setBlocks(result.blocks||[])}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}},[api,objectID])
  useEffect(()=>{void load()},[load,currentRevision])
  const lockedIDs=useMemo(()=>blocks.filter(item=>item.locked).map(item=>item.block_id),[blocks])
  async function toggle(blockID:string){
    setBusy(true);setError('');setNotice('');setPreview(undefined)
    const next=lockedIDs.includes(blockID)?lockedIDs.filter(id=>id!==blockID):[...lockedIDs,blockID]
    try{
      const result=await api.put<{blocks:ProductBlock[]}>(`/v1/knowledge-products/${encodeURIComponent(objectID)}/block-locks`,{expected_revision:currentRevision,block_ids:next})
      setBlocks(result.blocks||[])
      setNotice(next.includes(blockID)?'已锁定这个内容块；后续自动刷新只能保留人工 current。':'已解除内容块锁；下一次自动刷新可重新接管该块。')
    }catch(reason){setError(reason instanceof Error?reason.message:String(reason))}
    finally{setBusy(false)}
  }
  async function buildPreview(){
    setBusy(true);setError('');setNotice('')
    try{setPreview(await api.get<MergePreview>(`/v1/knowledge-products/${encodeURIComponent(objectID)}/merge-preview`))}
    catch(reason){setError(reason instanceof Error?reason.message:String(reason))}
    finally{setBusy(false)}
  }
  return <section className="product-block-governance">
    <header><div><LockKeyhole size={14}/><div><strong>Block-level 自动重建保护</strong><small>按 Markdown `##` section 锁定；不改变 Knowledge Product v1 payload schema。</small></div></div>{autoGenerated&&<button className="button" disabled={busy} onClick={()=>void buildPreview()}><GitCompareArrows size={13}/>{busy?'正在计算…':'三方 Merge 预览'}</button>}</header>
    {notice&&<p className="surface-notice">{notice}</p>}{error&&<p className="form-error">{error}</p>}
    <div className="product-block-list">{blocks.map(block=><article key={block.block_id} className={block.locked?'locked':''}>
      <div><div><strong>{block.label}</strong><code>{block.content_hash.slice(0,10)}</code></div><button className="text-button" disabled={busy} onClick={()=>void toggle(block.block_id)}>{block.locked?<><UnlockKeyhole size={12}/>解除 Block 锁</>:<><LockKeyhole size={12}/>锁定此 Block</>}</button></div>
      <p>{block.content.slice(0,180)}{block.content.length>180?'…':''}</p>{block.locked&&<small>锁定基线 R{block.lock_base_revision||'—'} · {block.lock_base_hash?.slice(0,10)||'—'}</small>}
    </article>)}</div>
    {preview&&<div className={`product-merge-preview ${preview.has_conflicts?'has-conflict':''}`}><header><div>{preview.has_conflicts?<ShieldAlert size={14}/>:<RefreshCw size={14}/>}<strong>{preview.has_conflicts?'存在锁定分歧，需要 Owner 复核':'三方 Merge 可安全执行'}</strong></div><code>candidate {preview.candidate_body_hash.slice(0,10)}</code></header>
      <div>{preview.blocks.map(block=><details key={block.block_id} className={block.requires_owner?'requires-owner':''}><summary><span>{block.label}</span><b>{block.status}</b></summary><div className="product-merge-columns"><article><small>BASE</small><pre>{block.base||'—'}</pre></article><article><small>CURRENT</small><pre>{block.current||'—'}</pre></article><article><small>CANDIDATE</small><pre>{block.candidate||'—'}</pre></article><article><small>MERGED</small><pre>{block.merged||'—'}</pre></article></div></details>)}</div>
      <small>自动刷新只会写入 MERGED；锁定 Block 出现双向分歧时仍保留 current，不会自动裁决。</small>
    </div>}
  </section>
}
